return {
	"nvimdev/dashboard-nvim",
	event = "UIEnter",
	dependencies = "nvim-tree/nvim-web-devicons",
	opts = {
		theme = "doom",
		config = {
			header = {
				[[                                                                       ]],
				[[                                                                       ]],
				[[                                                                       ]],
				[[                                                                     ]],
				[[       ████ ██████           █████      ██                     ]],
				[[      ███████████             █████                             ]],
				[[      █████████ ███████████████████ ███   ███████████   ]],
				[[     █████████  ███    █████████████ █████ ██████████████   ]],
				[[    █████████ ██████████ █████████ █████ █████ ████ █████   ]],
				[[  ███████████ ███    ███ █████████ █████ █████ ████ █████  ]],
				[[ ██████  █████████████████████ ████ █████ █████ ████ ██████ ]],
				[[                                                                       ]],
				[[                                                                       ]],
				[[                                                                       ]],
			},
			center = {
				{
					icon = "󰒲 ",
					icon_hl = "group",
					desc = "Lazy",
					desc_hl = "group",
					key = "l",
					key_hl = "group",
					key_format = " [%s]",
					action = ":Lazy",
				},
				{
					icon = " ",
					icon_hl = "group",
					desc = "Mason",
					desc_hl = "group",
					key = "m",
					key_hl = "group",
					key_format = " [%s]",
					action = ":Mason",
				},
				{
					icon = " ",
					icon_hl = "group",
					desc = "Telescope",
					desc_hl = "group",
					key = "t",
					key_hl = "group",
					key_format = " [%s]",
					action = ":Telescope",
				},
				{
					icon = "󰈆 ",
					icon_hl = "group",
					desc = "Quit",
					desc_hl = "group",
					key = "q",
					key_hl = "group",
					key_format = " [%s]",
					action = ":q",
				},
			},
		},
	},
}
